# Generated by Django 3.1.7 on 2021-07-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
